### PR TITLE
Fixes #14. Perform tokenCache operations with caution.

### LINKED ISSUE #14: Exception when using ADAL cordova on a encrypted android phone
I am developing a cordova app that uses ADAL cordova and requires a service from a corp network (MSFT corp network). ADAL cordova works using an emulator, but on a real device (which requires encryption to access the corp network) ADAL cordova is giving me an exception. The following is the exact error:

E/PluginManager(18227): Uncaught exception from plugin
E/PluginManager(18227): java.lang.ClassCastException: com.microsoft.aad.adal.AuthenticationContext$1 cannot be cast to com.microsoft.aad.adal.DefaultTokenCacheStore
E/PluginManager(18227):    at com.microsoft.aad.adal.CordovaAdalPlugin.readTokenCacheItems(CordovaAdalPlugin.java:165)
E/PluginManager(18227):    at com.microsoft.aad.adal.CordovaAdalPlugin.execute(CordovaAdalPlugin.java:83)
E/PluginManager(18227):    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
E/PluginManager(18227):    at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
E/PluginManager(18227):    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
E/PluginManager(18227):    at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
E/PluginManager(18227):    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/PluginManager(18227):    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
E/PluginManager(18227):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/PluginManager(18227):    at android.os.Looper.loop(Looper.java:145)
E/PluginManager(18227):    at android.os.HandlerThread.run(HandlerThread.java:61)

And the following is my code:
$scope.context = new Microsoft.ADAL.AuthenticationContext(authority);

    $scope.context.tokenCache.readItems().then(function (items) {
      if (items.length > 0) {
        authority = items[0].authority;
        $scope.context = new Microsoft.ADAL.AuthenticationContext(authority);
      }

      // Attempt to authorize user silently
      $scope.context.acquireTokenSilentAsync(resourceUrl, appId)
      .then(onAADSuccess, function () {
      // We require user cridentials so triggers authentication dialog
      $scope.context.acquireTokenAsync(resourceUrl, appId, redirectUrl)
     .then(onAADSuccess, function (err) {
        });
      });
    });

Any help would be appreciated!

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This fixes application silent crash when authentication broker is
available  on device (e.g. when Company Portal app is installed)

### CODE REVIEW

File: src/android/CordovaADAL/src/com/microsoft/aad/adal/CordovaAdalPlugin.java [hunk 1]
```diff
@@ -122,12 +122,14 @@ private boolean acquireTokenAsync(String authority, String resourceUrl, String c
...
 
         if (userId != null) {
-            ArrayList<TokenCacheItem> tokensForUserId =
-                    ((DefaultTokenCacheStore)authContext.getCache()).getTokensForUser(userId);
-
-            if (tokensForUserId.size() > 0) {
-                // Try to acquire alias for specified userId
-                userId = tokensForUserId.get(0).getUserInfo().getDisplayableId();
+            ITokenCacheStore cache = authContext.getCache();
+            if (cache instanceof ITokenStoreQuery) {
```
Comment (daserge) [inline src/android/CordovaADAL/src/com/microsoft/aad/adal/CordovaAdalPlugin.java]: Is this `false` in case of Company Portal app is installed?

**Comment by daserge** [comment]
Does this require `AuthenticationSettings.Instance.setSkipBroker(true);` as well?

File: src/android/CordovaADAL/src/com/microsoft/aad/adal/CordovaAdalPlugin.java (hunk 1 above)
Comment (vladimir-kotikov) [inline src/android/CordovaADAL/src/com/microsoft/aad/adal/CordovaAdalPlugin.java]: Yes. Only `DefaultTokenCacheStore` implements this interface. In case if Company portal is installed, context returns instance of 'ITokenCacheStore' interface.

**Comment by vladimir-kotikov** [comment]
No. I've made some additional testing, and it appears that this will work with Broker correctly.
